_target_: grt.models.SpectrumTokenizer
d_model: ${size.d_model}
patch:  # (time, doppler, elevation, azimuth, range)
- 1
- 2
- ${array.elevation}
- ${array.azimuth}
- 4
squeeze: [2, 3]  # elevation + azimuth
n_channels: 3  # (amplitude, sin(angle), cos(angle))
scale: [16.0, 16.0, 16.0]
w_min: 0.2
positions: nd
